---

- name: Check if deno is installed.
  stat:
    path: "/usr/local/deno"
  register: deno_bin

- name: Install curl
  apt:
    name: curl
    state: present

- name: Copy deno install script file
  copy:
    src: deno-install.sh
    dest: "/home/{{ ansible_user }}/"
    mode: "0755"
  when:
    - not deno_bin.stat.exists

- name: Install deno
  shell: "/home/{{ ansible_user }}/deno-install.sh"
  when:
    - not deno_bin.stat.exists

- name: Remove deno install script
  file:
    path: "/home/{{ ansible_user }}/deno-install.sh"
    state: absent
  when:
    - not deno_bin.stat.exists